"""change colum of regime.

Revision ID: 694d0a423321
Revises: 8e8a9e1f5f0a
Create Date: 2024-06-15 23:43:07.882488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694d0a423321'
down_revision: Union[str, None] = '8e8a9e1f5f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regimes', sa.Column('unidade_id', sa.Integer(), nullable=True))
    op.drop_constraint('regimes_parent_id_fkey', 'regimes', type_='foreignkey')
    op.create_foreign_key(None, 'regimes', 'unidades', ['unidade_id'], ['id'])
    op.drop_column('regimes', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regimes', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'regimes', type_='foreignkey')
    op.create_foreign_key('regimes_parent_id_fkey', 'regimes', 'unidades', ['parent_id'], ['id'])
    op.drop_column('regimes', 'unidade_id')
    # ### end Alembic commands ###
